before_script: "./script/bootstrap"
script: "./script/test"

#environment
language: ruby
rvm:
  - 2.4.0

notifications:
  email: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
cache: bundler
